import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import { BranchContextProvider } from "@/providers/useBranchData";
import ModalProvider from "@/providers/ModalProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <BranchContextProvider>
            <ModalProvider />
            {children}
        </BranchContextProvider>
      </body>
    </html>
  );
}
